import { transporter } from "./emailTransporter.js";
import { EMAIL_CONFIG } from "../../config/emailConfig.js";

/* ================= HELPERS ================= */
const formatOrderAmount = (order) => {
  if (
    order.paymentGateway === "stripe" &&
    order.convertedTotal &&
    order.currency
  ) {
    return `${order.currency} ${order.convertedTotal.toFixed(
      2
    )} (≈ ₹${order.total.toFixed(2)})`;
  }

  return `₹${order.total.toFixed(2)}`;
};

/* ================= ADMIN: QUOTE ================= */
export const sendAdminQuoteEmail = async (quote) => {
  const hasMessage = Boolean(quote.message);
  const hasItems = Array.isArray(quote.items) && quote.items.length > 0;

  const itemsHtml = hasItems
    ? quote.items
        .map(
          (item) => `
          <tr>
            <td style="padding:8px;border:1px solid #e5e7eb;">${item.name}</td>
            <td style="padding:8px;border:1px solid #e5e7eb;">${item.partNumber || "—"}</td>
            <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">${item.quantity}</td>
          </tr>
        `
        )
        .join("")
    : "";

  await transporter.sendMail({
    from: `"MAE Electricals" <${EMAIL_CONFIG.user}>`,
    to: EMAIL_CONFIG.staff,

    // ✅ ADDED (customer in CC)
    cc: quote.customer?.email,

    subject: `New Quote Request — ${quote.customer?.name || "Customer"}`,

    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;background:#f4f6f8;padding:24px;">
        <div style="max-width:720px;margin:auto;background:#ffffff;padding:24px;border-radius:6px;border:1px solid #e5e7eb;">

          <h2 style="margin-top:0;color:#6b21a8;">New Quote Request</h2>

          <p><strong>Name:</strong> ${quote.customer?.name || "—"}</p>
          <p><strong>Email:</strong> ${quote.customer?.email || "—"}</p>
          <p><strong>Company:</strong> ${quote.customer?.company || "—"}</p>

          ${
            quote.yourReference
              ? `<p><strong>Reference:</strong> ${quote.yourReference}</p>`
              : ""
          }

          ${
            hasMessage
              ? `
                <h3 style="margin-top:24px;">Customer Requirement</h3>
                <pre style="background:#f9fafb;padding:14px;border-radius:6px;border:1px solid #e5e7eb;white-space:pre-wrap;">
${quote.message}
                </pre>
              `
              : hasItems
              ? `
                <h3 style="margin-top:24px;">Requested Products</h3>
                <table style="width:100%;border-collapse:collapse;font-size:14px;">
                  <thead>
                    <tr style="background:#f9fafb;">
                      <th style="padding:8px;border:1px solid #e5e7eb;text-align:left;">Product</th>
                      <th style="padding:8px;border:1px solid #e5e7eb;text-align:left;">Part No</th>
                      <th style="padding:8px;border:1px solid #e5e7eb;">Qty</th>
                    </tr>
                  </thead>
                  <tbody>${itemsHtml}</tbody>
                </table>
              `
              : `<p style="margin-top:24px;color:#6b7280;">No product details provided.</p>`
          }

          <p style="margin-top:24px;font-size:12px;color:#6b7280;">
            This email was automatically generated by MAE Electricals.
          </p>
        </div>
      </div>
    `,

    // ✅ ADDED (attachment)
    attachments: quote.attachment
      ? [
          {
            filename: quote.attachment.split("/").pop(),
            path: quote.attachment,
          },
        ]
      : [],
  });
};

/* ================= ADMIN: ORDER ================= */
export const sendAdminOrderEmail = async (order) => {
  const itemsHtml = order.items
    .map(
      (item) => `
        <tr>
          <td style="padding:8px;border:1px solid #e5e7eb;">${item.name}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;">${item.partNumber || "—"}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;">${item.quantity}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:right;">₹${item.unitPrice.toFixed(2)}</td>
          <td style="padding:8px;border:1px solid #e5e7eb;text-align:right;">₹${item.lineTotal.toFixed(2)}</td>
        </tr>
      `
    )
    .join("");

  await transporter.sendMail({
    from: `"MAE Electricals" <${EMAIL_CONFIG.user}>`,
    to: EMAIL_CONFIG.staff,
    subject: `New Order Received — ${order.orderNumber}`,
    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;background:#f4f6f8;padding:24px;">
        <div style="max-width:760px;margin:auto;background:#ffffff;padding:24px;border-radius:6px;border:1px solid #e5e7eb;">

          <h2 style="margin-top:0;color:#6b21a8;">New Order Received</h2>

          <p><strong>Order Number:</strong> ${order.orderNumber}</p>
          <p><strong>Status:</strong> ${order.status}</p>
          <p><strong>Total:</strong> ${formatOrderAmount(order)}</p>

          <h3 style="margin-top:24px;">Ordered Items</h3>

          <table style="width:100%;border-collapse:collapse;font-size:14px;">
            <tbody>${itemsHtml}</tbody>
          </table>
        </div>
      </div>
    `,
  });
};

export const sendAdminPaymentEmail = async (order) => {
  await transporter.sendMail({
    from: `"MAE Electricals" <${EMAIL_CONFIG.user}>`,
    to: EMAIL_CONFIG.staff,
    subject: `💰 Payment Received — ${order.orderNumber}`,
    html: `
      <h2>Payment Received</h2>
      <p><strong>Order:</strong> ${order.orderNumber}</p>
      <p><strong>Amount:</strong> ${formatOrderAmount(order)}</p>
      <p><strong>Gateway:</strong> ${order.paymentGateway}</p>
      <p>Status updated to <strong>PAID</strong>.</p>
    `,
  });
};